source 'https://rubygems.org'
ruby '2.4.4'

gem 'jbuilder', '~> 2.9'
gem 'pg'
gem 'puma'
gem 'rails', '5.2.4.1'
gem 'redis'
gem 'devise', '>= 4.6.0'
gem 'faker', git: 'https://github.com/stympy/faker.git', branch: 'master'
gem 'pundit'
gem 'geocoder'
gem 'figaro'
gem 'cloudinary'
gem 'carrierwave', '~> 2.1'

gem 'autoprefixer-rails'
gem 'bootstrap-sass', '>= 3.4.1'
gem 'font-awesome-sass'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'
gem 'webpacker'

group :development, :test do
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
